import { FilteredRelease } from '../types/discogs';

export const DEMO_RELEASES: FilteredRelease[] = [
  {
    id: 1001,
    instance_id: 1001,
    basic_information: {
      id: 1001,
      title: 'Kind of Blue',
      artists: [{ name: 'Miles Davis', id: 101 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1959,
      genres: ['Jazz'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Jazz',
  },
  {
    id: 1002,
    instance_id: 1002,
    basic_information: {
      id: 1002,
      title: 'Rumours',
      artists: [{ name: 'Fleetwood Mac', id: 102 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1977,
      genres: ['Rock'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Rock',
  },
  {
    id: 1003,
    instance_id: 1003,
    basic_information: {
      id: 1003,
      title: 'Thriller',
      artists: [{ name: 'Michael Jackson', id: 103 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1982,
      genres: ['Pop'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Pop',
  },
  {
    id: 1004,
    instance_id: 1004,
    basic_information: {
      id: 1004,
      title: 'Purple Rain',
      artists: [{ name: 'Prince', id: 104 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1984,
      genres: ['Pop'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Pop',
  },
  {
    id: 1005,
    instance_id: 1005,
    basic_information: {
      id: 1005,
      title: 'Blue Lines',
      artists: [{ name: 'Massive Attack', id: 105 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1991,
      genres: ['Electronic'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Electronic',
  },
  {
    id: 1006,
    instance_id: 1006,
    basic_information: {
      id: 1006,
      title: 'Nevermind',
      artists: [{ name: 'Nirvana', id: 106 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1991,
      genres: ['Rock'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Rock',
  },
  {
    id: 1007,
    instance_id: 1007,
    basic_information: {
      id: 1007,
      title: 'Ready to Die',
      artists: [{ name: 'The Notorious B.I.G.', id: 107 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1994,
      genres: ['Hip-Hop'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Hip-Hop',
  },
  {
    id: 1008,
    instance_id: 1008,
    basic_information: {
      id: 1008,
      title: 'What\'s Going On',
      artists: [{ name: 'Marvin Gaye', id: 108 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1971,
      genres: ['Funk / Soul'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Funk / Soul',
  },
  {
    id: 1009,
    instance_id: 1009,
    basic_information: {
      id: 1009,
      title: 'Tapestry',
      artists: [{ name: 'Carole King', id: 109 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1971,
      genres: ['Pop'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Pop',
  },
  {
    id: 1010,
    instance_id: 1010,
    basic_information: {
      id: 1010,
      title: 'The Dark Side of the Moon',
      artists: [{ name: 'Pink Floyd', id: 110 }],
      formats: [{ name: 'LP', descriptions: ['Album'] }],
      thumb: '',
      cover_image: '',
      year: 1973,
      genres: ['Rock'],
    },
    primaryFormat: 'LP',
    primaryGenre: 'Rock',
  },
];
